title: AI Conference Deadlines
description: Countdowns to top CV/NLP/ML/Robotics/AI conference deadlines
author: Alexander Naumann

domain: "deadlines.info"
baseurl: ""

twitter_username: AlexN4u
twitter_hashtag: machinelearning
github_username: a-nau
github_repo: conference-deadlines

conference_threshold_millisec: 31557600000 # show only conference with deadlines before...

markdown: kramdown
ga_id: UA-166050497-2

include: ["_pages"]
