title: Logistics Conference Deadlines
description: Countdowns to Logistics/Robotics/AI conference deadlines. Overview of deadlines and conference dates in a calendar.
author: Alexander Naumann

domain: "https://kit-ifl.github.io"
baseurl: "/conference-deadlines"

github_username: KIT-IFL
github_repo: conference-deadlines
conference_threshold_millisec: 31557600000 # show only conference with deadlines before...

markdown: kramdown

include: ["_pages"]
