title: AI Conference Deadlines
description: Countdowns to top CV/NLP/ML/Robotics/AI conference deadlines
author: Alexander Naumann

domain: "https://a-nau.github.io/"
baseurl: "/conference-deadlines"

twitter_username: AlexN4u
twitter_hashtag: machinelearning
github_username: a-nau
github_repo: conference-deadlines

markdown: kramdown
ga_id: UA-36274081-2

include: ['_pages']